### ISSUE TITLE
TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by Jarvis1010** [akiran/react-highlight#39] opened 2017-09-27 14:30 UTC
Upgraded to React 16 last night and now the react highlight throws the above error

**Comment by briancappello** [comment] 2017-10-07 00:32
Until a fix gets merged, I've uploaded a branch to my fork that includes the compiled assets. It can be installed like so from package.json:

```json
"dependencies": {
    // ...
    "react-highlight": "briancappello/react-highlight#react-v16-compiled"
}
```

**Comment by mlynch** [comment] 2017-10-11 18:16
@briancappello Thanks for doing that. Unfortunately still seeing issues using your branch. Will add more if I find anything:

<img width="1274" alt="screen shot 2017-10-11 at 1 15 02 pm" src="https://user-images.githubusercontent.com/11214/31458664-628839cc-ae86-11e7-8347-b4f2a8e2d011.png">

**Comment by briancappello** [comment] 2017-10-11 20:32
@mlynch Can you share what your code looks like when you're using the Highlight component? I suspect the error you're seeing is related to using a custom element prop, which as best I could tell isn't documented and therefore I just guessed (apparently wrongly :-O) at what kinds of inputs it was supposed to work with.

**Comment by mlynch** [comment] 2017-10-16 17:53
@briancappello here's how it's being used:

<img width="586" alt="screenshot 2017-10-16 12 51 43" src="https://user-images.githubusercontent.com/11214/31626877-e5019ba8-b270-11e7-8b5f-b0ccb78c81ae.png">

**Comment by briancappello** [comment] 2017-10-16 18:20
@mlynch Interesting, looks to me like it *should* be working :/

Just to verify the bug really is somewhere in my PR, can you confirm the same code worked with React 0.15, and that no error happens if you do this with React 0.16?:

```js
{context && (
<pre>
  <code className="error-mapped-context typescript">
    {context}
  </code>
</pre>
)}
```
(It won't render highlighted, but it also shouldn't blow up)

**Comment by mlynch** [comment] 2017-10-16 18:27
@briancappello thanks. Yep this worked in React 15, and changing the 16 version to your code above makes it work without issue (no highlighting, of course)

**Comment by briancappello** [comment] 2017-10-16 18:36
@mlynch Hrmph. I'm sad to say I'm at a loss on this one :(

**Comment by richdyang** [comment] 2017-11-16 02:41
++++++111111

**Comment by richburdon** [comment] 2017-11-29 17:41
Broken for me in 16 also.

**Comment by davidthornton** [comment] 2017-12-02 08:30
Would be nice to have a fix merged

**Comment by alechstong** [comment] 2017-12-04 06:35
@briancappello Thanks for the good work. I am using your branch. everything works except the innerHTML=true option, which doesn't seems to do anything. I managed to find a workaround with html-react-parser, but it is very ugly.

**Comment by briancappello** [comment] 2017-12-05 03:20
@alechstong I'm not sure I follow what you needed a workaround for? The `innerHTML` option is for when you want to highlight a block of trusted, pre-rendered HTML (ie not JSX, but a string of HTML from the backend). 

So, without innerHTML, this works (it wraps the children in `<pre><code></code></pre>`):

```javascript
<Highlight language="javascript">
  {`function foo() { return 'bar' }`}
</Highlight>
```

Whereas with innerHTML, there is no automatic wrapping:
```javascript
<Highlight innerHTML languages={['python', 'javascript']}>
  {`<p>This is a string of HTML. It has multiple blocks of code within it.</p>
   <pre><code>function foo() { return 'like this one' }</code></pre>
   <pre><code>def foo():\n    return 'and this one'</code></pre>
  `}
</Highlight>
```

**Comment by alechstong** [comment] 2017-12-05 04:58
@briancappello Thank you for replying. I tried your snippets, they do work. And I tried to reproduce the problem in my project, but I'm glad to see the problem's gone now. I remember that the innerHTML attrib didn't work for us, so we had to convert the string to react DOM and manually replace the code tag with Highlight. Must be something we did wrong.

**Comment by romainbessugesmeusy** [comment] 2017-12-11 09:48
Running React 16.2.0, app created with create-react-app, same error here. Seems to break here :

```javascript
    highlightCode() {
        const domNode = ReactDOM.findDOMNode(this);
        const nodes = domNode.querySelectorAll('pre code');
```

**Comment by ajGingrich** [comment] 2017-12-22 23:03
I also am having problems in React 16.2 with error `Uncaught TypeError: Cannot read property 'querySelectorAll' of null at Highlight.highlightCode (index.js:52) at Highlight.componentDidMount`

**Comment by discoduke** [comment] 2017-12-31 00:43
I'm also having a problem with this in React 16.2.  As far as I can tell, both React.DOM.div and ReactDOM.findDOMNode are now deprecated in React 16.  The preferred method is to use {ref} in the render method to store a reference to specific element.  

As far as I can tell 'Highlight innerHTML' is still working as expected -- I can see the pre/code elements in the original page source.  But when componentDidMount/highlightCode executes (after page load), ReactDOM.findDOMNode(this) returns null.

**Comment by briancappello** [comment] 2017-12-31 01:17
@discoduke I believe you are correct. I opened a PR (#43) a while ago that drops the deprecated stuff and uses ref instead. Sadly, I've heard nothing but radio silence from @akiran. See [my comment above](https://github.com/akiran/react-highlight/issues/39#issuecomment-334898100) if you want to try it out.

**Comment by gihrig** [comment] 2018-01-05 17:52
@briancappello Your patch works for me! 🎉 

I'm following this Learn Next JS [lesson](https://learnnextjs.com/excel/lazy-loading-components/setup).

I hope @akiran is OK...

**Comment by alexMaluco** [comment] 2018-01-08 11:55
Thanks @briancappello!

**Comment by znafets** [comment] 2018-01-19 10:06
Thanks @briancappello! Works like a charm.
```
"dependencies": {
    "cross-env": "^5.0.1",
    "marked": "^0.3.6",
    "next": "^4.2.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-highlight": "briancappello/react-highlight#react-v16-compiled",
    "webpack-bundle-analyzer": "^2.8.3"
  }
```

**Comment by RahavLussato** [comment] 2018-02-18 09:43
@mlynch try to change the require from `const Highlight = require('react-highlight');`
to `import Highlight from 'react-highlight';`

**Comment by adammenges** [comment] 2018-02-18 22:39
Hitting this now too, trying @briancappello's patch.

**Comment by johngrimes** [comment] 2018-02-18 22:57
Here's what I did when I encountered this error:

1. Went to https://highlightjs.org/download/ and got the minimal package of files for what I need (which was much smaller than what `react-highlight` was bringing in).
2. Extracted this into `src/vendor/highlight`.
3. Used it within my React component something like this:

```javascript
import Highlight from './vendor/highlight'

class SomeComponent extends Component {
  constructor(props) {
    super(props)
    this.highlightCode = this.highlightCode.bind(this)
  }

  componentDidMount() { this.highlightCode() }
  componentDidUpdate() { this.highlightCode() }

  highlightCode() {
    if (this.code) Highlight.highlightBlock(this.code)
  }

  render() {
    return <pre className="json" ref={el => { this.code = el }}>{this.props.someCode}</pre>
  }
}
```

Then I just removed the dependency on `react-highlight`!

Anybody see any downsides to this approach? I can't see that this module is really buying me much at this point.

**Comment by Ajk4** [comment] 2018-03-10 18:31
Thx @johngrimes for snippet, I hit this problem too and you snippet is helpful.

**Comment by mbj36** [comment] 2018-03-14 04:32
We have published new version with React 16 support

**Closed by mbj36** 2018-03-14 04:32 UTC
